<a href="https://colab.research.google.com/github/Margo-s-M/AI_Colab/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pandas_S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [51]:
import numpy as np
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [52]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

In [53]:
df

     pclass     sex   age  sibsp  parch     fare embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [54]:
df.shape

(891, 7)

In [55]:
df.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'], dtype='object')

In [56]:
df.dtypes

pclass        int64
sex          object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
dtype: object

In [57]:
df.isnull().sum()

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [59]:
(df['embarked'] == 'C').sum()

168

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [60]:
df

     pclass     sex   age  sibsp  parch     fare embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [61]:
df[['sex', 'age' ,'fare' ]]

        sex   age     fare
0      male  22.0   7.2500
1    female  38.0  71.2833
2    female  26.0   7.9250
3    female  35.0  53.1000
4      male  35.0   8.0500
..      ...   ...      ...
886    male  27.0  13.0000
887  female  19.0  30.0000
888  female   NaN  23.4500
889    male  26.0  30.0000
890    male  32.0   7.7500

[891 rows x 3 columns]

In [62]:
df['pclass'] ==1
mask =df['pclass'] ==1

In [63]:
df[['sex', 'age' ,'fare' ]]

        sex   age     fare
0      male  22.0   7.2500
1    female  38.0  71.2833
2    female  26.0   7.9250
3    female  35.0  53.1000
4      male  35.0   8.0500
..      ...   ...      ...
886    male  27.0  13.0000
887  female  19.0  30.0000
888  female   NaN  23.4500
889    male  26.0  30.0000
890    male  32.0   7.7500

[891 rows x 3 columns]

In [64]:
df[['sex', 'age' ,'fare' ,'embarked' ]][df['pclass'] ==3]

        sex   age     fare embarked
0      male  22.0   7.2500        S
2    female  26.0   7.9250        S
4      male  35.0   8.0500        S
5      male   NaN   8.4583        Q
7      male   2.0  21.0750        S
..      ...   ...      ...      ...
882  female  22.0  10.5167        S
884    male  25.0   7.0500        S
885  female  39.0  29.1250        Q
888  female   NaN  23.4500        S
890    male  32.0   7.7500        Q

[491 rows x 4 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

In [65]:
df['age'] <18
mask1 = df['age'] <18

In [66]:
df.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'], dtype='object')

In [67]:
df['embarked'] =='C'
mask2 = df['embarked'] =='C'

In [68]:
df['sex'] == 'male'
mask3 = df['sex'] == 'male'

In [69]:
mask = mask1 & mask2 & mask3
df[mask].shape

(7, 7)

In [71]:
df[(df['age'] <18) & (df['embarked'] =='C') & (df['sex'] == 'male')]

     pclass   sex    age  sibsp  parch      fare embarked
125       3  male  12.00      1      0   11.2417        C
352       3  male  15.00      1      1    7.2292        C
532       3  male  17.00      1      1    7.2292        C
550       1  male  17.00      0      2  110.8833        C
731       3  male  11.00      0      0   18.7875        C
803       3  male   0.42      0      1    8.5167        C
827       2  male   1.00      0      2   37.0042        C

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [72]:
df[['sibsp' ,'parch']]

     sibsp  parch
0        1      0
1        1      0
2        0      0
3        1      0
4        0      0
..     ...    ...
886      0      0
887      0      0
888      1      2
889      0      0
890      0      0

[891 rows x 2 columns]

In [73]:
df['sibsp'] + df['parch']

0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    3
889    0
890    0
Length: 891, dtype: int64

In [74]:
df['relatives'] = df['sibsp'] + df['parch']

In [75]:
df

     pclass     sex   age  sibsp  parch     fare embarked  relatives
0         3    male  22.0      1      0   7.2500        S          1
1         1  female  38.0      1      0  71.2833        C          1
2         3  female  26.0      0      0   7.9250        S          0
3         1  female  35.0      1      0  53.1000        S          1
4         3    male  35.0      0      0   8.0500        S          0
..      ...     ...   ...    ...    ...      ...      ...        ...
886       2    male  27.0      0      0  13.0000        S          0
887       1  female  19.0      0      0  30.0000        S          0
888       3  female   NaN      1      2  23.4500        S          3
889       1    male  26.0      0      0  30.0000        C          0
890       3    male  32.0      0      0   7.7500        Q          0

[891 rows x 8 columns]

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками